### PR TITLE
Log sass-lint formatted report only if errors and warnings were found

### PR DESCRIPTION
**Pull request by troch**
Related to issue #7

### CODE REVIEW

**Comment by troch** [comment]
Bump :+1:

**Comment by samuelmartineau** [comment]
:+1:

I also expect that improvement

**Comment by Snugug** [comment]
Sass Lint now handles this internally
https://github.com/sasstools/sass-lint/blob/develop/index.js#L101-L131

And we should use that.

**Comment by itsthatguy** [comment]
after testing with `1.3.0` of sass-lint, it does not appear to address the problem that this PR is trying to resolve.

**Comment by itsthatguy** [comment]
Here's an alternate way of determining if there is anything to report or not, without that magic array index of 0.

``` javascript
    var messageCount = 0;
    file.sassLint.forEach((f) => { messageCount += f.warningCount + f.errorCount; });
    if (messageCount) { gutil.log(lint.format(file.sassLint)); }
```

**Comment by troch** [comment]
`.some` is more appropriate for this then:

``` javascript
var hasMessagesToLog = file.sassLint.some(function(f) {
    return f.warningCount + f.errorCount > 0;
});
```

**Comment by fernandofleury** [comment]
so, no feedback on it?

**Comment by danimalweb** [comment]
+1

**Comment by danimalweb** [comment]
Nice one @troch fingers crossed this gets merged soon :) @Snugug Can you merge this in to master?

**Comment by alebelcor** [comment]
Looking forward to this :grin:

**Comment by akullpp** [comment]
+1

**Comment by mrchimp** [comment]
+2

**Comment by Snugug** [comment]
In progress

**Pull request closed without merging**
