### PR TITLE
Drop dependency on deprecated `gulp-util`

### LINKED ISSUE #83: Remove deprecated module gulp-util
Replace deprecated dependency gulp-util

[`gulp-util`](https://www.npmjs.com/package/gulp-util) has been recently deprecated. Continuing to use this dependency may prevent the use of your library with the latest release of Gulp 4 so **it is important to replace `gulp-util`**.

The [README.md](https://github.com/gulpjs/gulp-util) lists alternatives for all the components so a simple replacement should be enough.

Your package is one of the most popular packages still relying on `gulp-util`, it would be good to publish a fixed version to npm as soon as possible.

See:
- https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
- https://github.com/gulpjs/gulp-util/issues/143

### PR DESCRIPTION
**Pull request by ghost**
Closes #83

### CODE REVIEW

**Review by demurgos — APPROVED** [review]
Looks good to me

@DanPurdy 
Could you merge and publish it?

**Comment by ghost** [comment]
@DanPurdy 
Did you get a chance to look at this?

**Comment by ghost** [comment]
Another friendly reminder.

**Comment by rejas** [comment]
A third friendly reminder :-)

**Comment by theenoahmason** [comment]
And a fourth friendly reminder. 🙏

**Comment by jameelmoses** [comment]
A 5th?

**Comment by rejas** [comment]
maybe we have to mention @DanPurdy or someone else from the team directly :-)

**Comment by xzyfer** [comment]
Hello, it looks like I still have privileges in this repository. I'll reach out to the maintainers about moving this forward. Please bare with me for the next couple days.

**Comment by jameelmoses** [comment]
For a project with 24,356 weekly downloads, I'd expect a bit more timeliness in response to issues/PRs. I understand the nature of open-source development, however, so I'm happy to put my money where my mouth is and contribute.

**Comment by theenoahmason** [comment]
Just pointing out that this pull request was made December of last year...

**Comment by ghost** [comment]
@xzyfer 
Did you reach out to the maintainers?

**Comment by xzyfer** [comment]
I have. I'm getting set up with the npm privileges and then I'll move this
forward. Thanks for you patience.

**Comment by xzyfer** [comment]
This should be fixed in 1.4.0

**Comment by jameelmoses** [comment]
@xzyfer thanks! are you able to get this update published in NPM?

**Comment by xzyfer** [comment]
It is as 1.4.0

**Pull request merged**
