### PR TITLE
Update to latest Sass Lint

### PR DESCRIPTION
**Pull request by mi2oon**
Just a version update for Sass lint package with the latest fixes

### CODE REVIEW

**Comment by thomasmattheussen** [comment]
:+1:

**Comment by DanPurdy** [comment]
This isn't necessary, If you delete your node modules and reinstall the latest version of gulp-sass-lint 1.4.0 will be installed anyway because it's specified with the `^` character which get the latest minor release.

from [npm](https://docs.npmjs.com/getting-started/semantic-versioning) itself.

> Patch releases: 1.0 or 1.0.x or ~1.0.4
> Minor releases: 1 or 1.x or ^1.0.4
> Major releases: \* or x

Once we go to version 2.x this will be necessary

**Comment by mi2oon** [comment]
@DanPurdy haha..totally overlooked that `^`. Anyway, thanks for the clarification :)

**Comment by DanPurdy** [comment]
No problem :+1:

**Comment by DanPurdy** [comment]
Also 1.5.0 is out now :smile:

**Comment by mi2oon** [comment]
@DanPurdy Ohh, gotta see what goodies it brings. I have a junior developer who been complaining when it breaks the watch process on various silly typos. :)

**Comment by DanPurdy** [comment]
yeah, that wont happen anymore. The parse errors just show as Fatal lint errors now but wont actually dump you out of anything unless you're using the CLI without the `--no-exit` flag

**Comment by mi2oon** [comment]
@DanPurdy  :+1: I now have a happy developer :grin:

**Pull request closed without merging**
