### PR TITLE
Update to 1.6 with new CLRF fixes.

### PR DESCRIPTION
**Pull request by gokunymbus**

### CODE REVIEW

**Comment by simeydotme** [comment]
can you make this 1.6.2 ? seems like there were some hotfixes

**Comment by gokunymbus** [comment]
Done!

**Comment by gokunymbus** [comment]
Can we merge this in?

**Comment by simeydotme** [comment]
I would like that, haven't been able to lint scss in my build flow since December because of a bug that was fixed in 1.6.0 :(

**Comment by bgriffith** [comment]
@battletoilet @simeydotme - Hey guys, will merge this (can you update it to `1.7` first) but just so you know, the  `^` in the version number  (`^1.5.1`) means that when you run `npm install` it will get the latest `1.x.x` version (i.e. it will install the latest version)

**Comment by zslabs** [comment]
Since this is based on sass-lint; shouldn't we just make sure the latest is always installed? Maybe make the version number as flexible as `1.*.*`

**Comment by Snugug** [comment]
https://github.com/sasstools/gulp-sass-lint/pull/5#issuecomment-137181328

**Pull request closed without merging**
